In [1]:
import torch

In [2]:
from torchvision.datasets import MNIST
dataset=MNIST(root='./data', download=True, train=True)
example=dataset[45]
print(example)
features, label = example
print(features)
print(label)
features.show()

(<PIL.Image.Image image mode=L size=28x28 at 0x7FE7F9D5BB20>, 9)
<PIL.Image.Image image mode=L size=28x28 at 0x7FE7F9D5BB20>
9


In [34]:
import pandas as pd
from tabular_data import hello
h = hello()
df = pd.read_csv("/Users/dq/Documents/aicore_project/Airbnb_Project/AirBnbData.csv")
df = h.clean_tabular_data(df)
df = df.iloc[:,:]
x, y = h.load_airbnb(df,"Price_Night")

In [35]:
x

Category  guests  beds  bathrooms  Cleanliness_rate  Accuracy_rate  \
0    Treehouses     2.0   1.0        1.0               4.6            4.7   
1    Treehouses     3.0   3.0        0.0               4.3            4.7   
2    Treehouses     4.0   2.0        1.5               4.2            4.6   
3    Treehouses     2.0   1.0        1.0               4.8            4.9   
5    Treehouses     4.0   3.0        1.0               5.0            4.9   
..          ...     ...   ...        ...               ...            ...   
982  Beachfront     4.0   2.0        1.5               4.9            5.0   
983  Beachfront     2.0   1.0        1.0               4.8            5.0   
984  Beachfront     4.0   2.0        1.5               4.8            5.0   
985  Beachfront     6.0   3.0        2.0               4.7            4.8   
987  Beachfront     4.0   2.0        1.0               4.9            4.9   

     Communication_rate  Location_rate  Check-in_rate  Value_rate  \
0                   4.3            5.0            4.3         4.3   
1                   4.6            4.9            4.7         4.5   
2                   4.8            4.8            4.8         4.7   
3                   4.9            4.9            5.0         4.6   
5                   5.0            4.7            5.0         4.7   
..                  ...            ...            ...         ...   
982                 5.0            5.0            4.9         4.8   
983                 4.9            4.9            5.0         4.9   
984                 5.0            5.0            5.0         4.8   
985                 5.0            5.0            5.0         4.7   
987                 4.9            4.9            4.9         4.3   

     amenities_count  bedrooms  
0               13.0       1.0  
1                8.0       1.0  
2               51.0       1.0  
3               23.0       1.0  
5               32.0       2.0  
..               ...       ...  
982             33.0       2.0  
983             54.0       1.0  
984             38.0       2.0  
985             24.0       2.0  
987             29.0       2.0  

[830 rows x 12 columns]

In [2]:
import pandas as pd
from torch.utils.data import Dataset
import torch
import numpy as np
from tabular_data import hello
h = hello()

import pandas as pd
from torch.utils.data import Dataset
import torch
import numpy as np
from tabular_data import hello
import re

class AirbnbNightlyPriceImageDataset(Dataset):
    def __init__(self):
        super().__init__()
        self.data = pd.read_csv("/Users/dq/Documents/aicore_project/Airbnb_Project/clean_tabular_data.csv")
        self.data=self.data.dropna(axis=0)
        self.data.dropna(subset=['bedrooms'], inplace=True)
        self.data.pop("ID")
        self.data.pop("Category")
        self.data.pop("Title")
        self.data.pop("Description")
        self.data.pop("Amenities")
        self.data.pop("Location")
        self.data.pop("url")

# class AirbnbNightlyPriceImageDataset(Dataset):

#     def __init__(self):
#         super().__init__()
#         self.data = pd.read_csv("/Users/dq/Documents/aicore_project/Airbnb_Project/clean_tabular_data.csv")
#         self.data.pop("Category")
#         self.data.pop("Unnamed: 0")
#         h = hello()
#         self.features, self.label = h.load_airbnb(self.data, 'Price_Night')

    def __getitem__(self, index):
        example = self.data.iloc[index]
        features = example[1:10]
        features=torch.tensor(features)
        label = torch.tensor(example['Price_Night'])
        return (features, label)

    def __len__(self):
        return len(self.data)

dataset = AirbnbNightlyPriceImageDataset()












In [4]:
dataset=AirbnbNightlyPriceImageDataset()

features, labels = dataset[1]

print(features) 
print(labels)

tensor([ 3.0000,  3.0000,  0.0000, 92.0000,  4.3000,  4.7000,  4.6000,  4.9000,
         4.7000], dtype=torch.float64)
tensor(92., dtype=torch.float64)


In [12]:
from torch.utils.data import DataLoader, random_split

train, test = random_split(dataset, [round(len(dataset)*0.8), round(len(dataset)*0.2)])
train, valid = random_split(dataset, [round(len(dataset)*0.75), round(len(dataset)*0.25)])

train_loader = DataLoader(train, batch_size=8, shuffle=True)
test_loader = DataLoader(test, batch_size=8, shuffle=True)
valid_loader = DataLoader(valid, batch_size=8, shuffle=True)


In [13]:
features, labels = next(iter(train_loader))

In [14]:
features.shape

torch.Size([8, 9])

In [15]:
next(iter(train_loader))

[tensor([[  2.0000,   1.0000,   1.0000,  71.0000,   5.0000,   4.9000,   4.9000,
            4.9000,   4.9000],
         [  4.0000,   2.0000,   2.0000, 103.0000,   5.0000,   5.0000,   5.0000,
            5.0000,   5.0000],
         [  6.0000,   5.0000,   2.0000, 146.0000,   4.8000,   4.8000,   4.9000,
            4.9000,   4.9000],
         [  4.0000,   1.0000,   1.0000, 186.0000,   4.9000,   5.0000,   5.0000,
            4.9000,   5.0000],
         [  2.0000,   1.0000,   1.5000, 125.0000,   4.9000,   4.9000,   4.9000,
            4.9000,   5.0000],
         [  4.0000,   4.0000,   1.0000,  75.0000,   4.8000,   4.9000,   4.9000,
            4.9000,   4.9000],
         [  4.0000,   2.0000,   1.5000, 115.0000,   4.9000,   5.0000,   5.0000,
            4.9000,   5.0000],
         [  3.0000,   1.0000,   1.0000, 170.0000,   4.8000,   4.9000,   5.0000,
            4.9000,   5.0000]], dtype=torch.float64),
 tensor([ 71., 103., 146., 186., 125.,  75., 115., 170.], dtype=torch.float64)]

In [16]:
next(iter(test_loader))

[tensor([[  2.0000,   1.0000,   2.0000,  19.0000,   4.6000,   4.9000,   4.9000,
            4.8000,   4.9000],
         [  4.0000,   3.0000,   2.0000, 100.0000,   5.0000,   5.0000,   5.0000,
            5.0000,   5.0000],
         [  4.0000,   2.0000,   1.0000, 171.0000,   4.9000,   5.0000,   4.9000,
            5.0000,   4.9000],
         [  2.0000,   1.0000,   1.0000, 109.0000,   5.0000,   5.0000,   5.0000,
            4.9000,   5.0000],
         [  2.0000,   1.0000,   1.0000,  88.0000,   4.9000,   4.9000,   5.0000,
            4.9000,   5.0000],
         [  2.0000,   1.0000,   1.0000, 112.0000,   4.9000,   5.0000,   5.0000,
            4.9000,   5.0000],
         [  2.0000,   1.0000,   1.0000,  69.0000,   4.8000,   4.9000,   4.9000,
            4.9000,   4.9000],
         [  5.0000,   5.0000,   1.0000, 425.0000,   4.9000,   5.0000,   5.0000,
            5.0000,   5.0000]], dtype=torch.float64),
 tensor([ 19., 100., 171., 109.,  88., 112.,  69., 425.], dtype=torch.float64)]

In [17]:
next(iter(valid_loader))

[tensor([[  4.0000,   2.0000,   1.0000, 108.0000,   4.9000,   4.8000,   4.8000,
            4.8000,   5.0000],
         [  2.0000,   1.0000,   1.0000,  91.0000,   4.9000,   4.9000,   4.9000,
            4.9000,   5.0000],
         [  2.0000,   1.0000,   1.0000,  86.0000,   4.9000,   4.9000,   5.0000,
            4.9000,   5.0000],
         [  6.0000,   1.0000,   1.0000,  77.0000,   4.8000,   4.8000,   4.9000,
            4.8000,   4.9000],
         [  4.0000,   3.0000,   1.0000, 109.0000,   4.8000,   5.0000,   5.0000,
            5.0000,   5.0000],
         [  2.0000,   2.0000,   1.5000, 120.0000,   5.0000,   5.0000,   5.0000,
            4.8000,   5.0000],
         [  2.0000,   1.0000,   1.0000, 166.0000,   4.9000,   5.0000,   5.0000,
            4.9000,   5.0000],
         [  2.0000,   1.0000,   2.0000,  19.0000,   4.6000,   4.9000,   4.9000,
            4.8000,   4.9000]], dtype=torch.float64),
 tensor([108.,  91.,  86.,  77., 109., 120., 166.,  19.], dtype=torch.float64)]

In [18]:
import torch.nn.functional as F
from torch.utils.tensorboard import SummaryWriter

class LinearRegression(torch.nn.Module):
    def __init__(self)->None:
        super().__init__()
        self.layers = torch.nn.Sequential(
            torch.nn.Linear(9, 1),
            torch.nn.ReLU(),
            torch.nn.Linear(9, 1)
        )
        self.double()
        
    def forward(self, features):
        return self.layers(features)

def train(model, epochs=10):
    optimiser = torch.optim.SGD(model.parameters(), lr=0.01)
    writer=SummaryWriter()
    batch_idx=0

    for epoch in range(epochs):
        for batch in train_loader:
            features, labels = batch
            prediction = model(features)
            loss = F.mse_loss(prediction, labels)
            loss.backward() #
            print(loss.item())
            optimiser.step() #
            optimiser.zero_grad() #
            writer.add_scalar('loss', loss.item(), batch_idx)
            batch_idx+=1

model = LinearRegression()
train(model, epochs=5)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (8x1 and 9x1)